theme: jekyll-theme-minimal
encoding: utf-8
lsi: false
safe: true
source: [ /docs ]
incremental: false
highlighter: rouge
gist:
  noscript: false
kramdown:
  math_engine: mathjax
  syntax_highlighter: rouge
