/*
 * This file was generated by the Gradle 'init' task.
 *
 * The settings file is used to specify which projects to include in your build.
 *
 * Detailed information about configuring a multi-project build in Gradle can be found
 * in the user manual at https://docs.gradle.org/6.8.2/userguide/multi_project_builds.html
 */

rootProject.name = "pf4k"
include(
    "pf4k-api",
    "pf4k-impl:pf4k-basic-impl",
    "pf4k-impl:pf4k-core-module-impl",
    "pf4k-impl:pf4k-pluggable-module-impl",
    "pf4k-impl:pf4k-module-management-impl",
    "pf4k-impl:pf4k-app-impl",
    "pf4k-impl:pf4k-app-launcher",
    "pf4k-plugins"
)
pluginManagement {
    plugins {
        id("maven-publish") apply false
        id("publishing") apply false
        id("common-build-plugin") apply false
    }
}