timezone: Europe/Moscow
theme: jekyll-theme-minimal
encoding: utf-8
lsi: false
safe: true
incremental: false
highlighter: rouge
gist:
  noscript: false
markdown: kramdown
kramdown:
  math_engine: mathjax
  syntax_highlighter: rouge
strict_front_matter: true
